FROM node:20-alpine AS builder

ENV NODE_ENV=development
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:20-alpine

ENV NODE_ENV=production
WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/src ./src
COPY --from=builder /usr/src/app/tsconfig*.json ./

USER node
EXPOSE 3000
CMD ["sh", "-c", "npm run migration:run && npm run seed:catalogs && node dist/main"]