version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development 
    container_name: barber_container_b
    ports:
      - "3000:3000"
    env_file:
      - .env # <--- Inyecta automáticamente las variables de entorno de Render
    volumes:
      # 1. Monta todo tu proyecto local en el contenedor para detectar cambios de código
      - .:/usr/src/app
      # 2. Security and permformance
      # Don't let that the machine node_module rewrite the container node_modules 
      - /usr/src/app/node_modules
      # 3. Evit conflicts if you have a binder dist compiled localy
      - /usr/src/app/dist
    environment:
      - NODE_ENV=development
    # Garantize automatic restart if the app fail as a result from  temporalsintax error 
    restart: unless-stopped
