services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: barber_container_prod
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    restart: unless-stopped