FROM node:20-alpine

ENV NODE_ENV=development
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000
CMD ["sh", "-c", "npm run migration:run && npm run seed:catalogs && npm run start:dev"]