services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: barber_container_dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      # 1. Rode the local proyecto on container to detect code changes
      - .:/usr/src/app
      # 2. Security and permformance
      # Don't let that the machine node_module rewrite the container node_modules 
      - /usr/src/app/node_modules
      # 3. Evit conflicts if you have a binder dist compiled localy
      - /usr/src/app/dist
    environment:
      - NODE_ENV=development
    restart: unless-stopped